export const GET_BOOKS = 'GET_BOOKS';
export const GET_MORE_BOOKS = 'GET_MORE_BOOKS';
export const GET_BOOKS_IS_FETCHING = 'GET_BOOKS_IS_FETCHING';
export const GET_BOOKS_IS_FAILURE = 'GET_BOOKS_IS_FAILURE';
export const GET_MORE_BOOKS_IS_FETCHING = 'GET_MORE_BOOKS_IS_FETCHING';

